### PR TITLE
Fix: d.for.Each is not a function errors

### LINKED ISSUE #2002: Query Type Triggers Count issue (d.for.Each is not a funtion)
**Describe the bug**

Ever since upgrading to the 5.0 plugin, an anomaly has arisen when querying the count through Query Type (Triggers) in the Acknowledged state, resulting in the error "d.forEach is not a function".

**Expected behavior**

The display should appear normally without any anomalies occurring.

**Screenshots**

Image

Panel JSON

```
{
  "id": 14,
  "type": "bargauge",
  "title": "Unacknowledged Alerts in Time Range",
  "gridPos": {
    "x": 0,
    "y": 7,
    "h": 7,
    "w": 13
  },
  "fieldConfig": {
    "defaults": {
      "mappings": [],
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "color": "green",
            "value": null
          },
          {
            "color": "red",
            "value": 80
          }
        ]
      },
      "color": {
        "mode": "thresholds"
      }
    },
    "overrides": [
      {
        "matcher": {
          "id": "byName",
          "options": "Count A"
        },
        "properties": [
          {
            "id": "displayName",
            "value": "Information"
          },
          {
            "id": "color",
            "value": {
              "fixedColor": "blue",
              "mode": "fixed"
            }
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "Count B"
        },
        "properties": [
          {
            "id": "displayName",
            "value": "Warning"
          },
          {
            "id": "color",
            "value": {
              "fixedColor": "orange",
              "mode": "fixed"
            }
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "Count C"
        },
        "properties": [
          {
            "id": "displayName",
            "value": "Average"
          },
          {
            "id": "color",
            "value": {
              "fixedColor": "super-light-red",
              "mode": "fixed"
            }
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "Count D"
        },
        "properties": [
          {
            "id": "displayName",
            "value": "High"
          },
          {
            "id": "color",
            "value": {
              "fixedColor": "red",
              "mode": "fixed"
            }
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "Count E"
        },
        "properties": [
          {
            "id": "displayName",
            "value": "Disaster"
          },
          {
            "id": "color",
            "value": {
              "fixedColor": "dark-red",
              "mode": "fixed"
            }
          }
        ]
      }
    ]
  },
  "transformations": [
    {
      "id": "calculateField",
      "options": {
        "binary": {
          "left": {
            "fixed": ""
          },
          "right": {
            "fixed": ""
          }
        },
        "mode": "binary",
        "reduce": {
          "reducer": "lastNotNull"
        }
      }
    }
  ],
  "transparent": true,
  "pluginVersion": "11.4.0",
  "targets": [
    {
      "application": {
        "filter": ""
      },
      "countTriggersBy": "",
      "evaltype": "0",
      "functions": [],
      "group": {
        "filter": "$hgroup"
      },
      "host": {
        "filter": "/.*/"
      },
      "item": {
        "filter": ""
      },
      "itemTag": {
        "filter": ""
      },
      "macro": {
        "filter": ""
      },
      "options": {
        "acknowledged": 1,
        "count": true,
        "disableDataAlignment": false,
        "hostProxy": false,
        "hostsInMaintenance": false,
        "limit": 1001,
        "minSeverity": 1,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "sortProblems": "default",
        "useTimeRange": true,
        "useTrends": "default",
        "useZabbixValueMapping": false
      },
      "proxy": {
        "filter": ""
      },
      "queryType": "4",
      "refId": "A",
      "resultFormat": "time_series",
      "schema": 12,
      "showProblems": "problems",
      "table": {
        "skipEmptyValues": false
      },
      "tags": {
        "filter": ""
      },
      "textFilter": "",
      "trigger": {
        "filter": ""
      }
    },
    {
      "application": {
        "filter": ""
      },
      "countTriggersBy": "",
      "datasource": {
        "type": "alexanderzobnin-zabbix-datasource",
        "uid": "ce7a1xu5vquiof"
      },
      "evaltype": "0",
      "functions": [],
      "group": {
        "filter": "$hgroup"
      },
      "hide": false,
      "host": {
        "filter": "/.*/"
      },
      "item": {
        "filter": ""
      },
      "itemTag": {
        "filter": ""
      },
      "macro": {
        "filter": ""
      },
      "options": {
        "acknowledged": 1,
        "count": true,
        "disableDataAlignment": false,
        "hostProxy": false,
        "hostsInMaintenance": false,
        "limit": 1001,
        "minSeverity": 2,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "sortProblems": "default",
        "useTimeRange": true,
        "useTrends": "default",
        "useZabbixValueMapping": false
      },
      "proxy": {
        "filter": ""
      },
      "queryType": "4",
      "refId": "B",
      "resultFormat": "time_series",
      "schema": 12,
      "showProblems": "problems",
      "table": {
        "skipEmptyValues": false
      },
      "tags": {
        "filter": ""
      },
      "textFilter": "",
      "trigger": {
        "filter": ""
      }
    },
    {
      "application": {
        "filter": ""
      },
      "countTriggersBy": "",
      "datasource": {
        "type": "alexanderzobnin-zabbix-datasource",
        "uid": "ce7a1xu5vquiof"
      },
      "evaltype": "0",
      "functions": [],
      "group": {
        "filter": "$hgroup"
      },
      "hide": false,
      "host": {
        "filter": "/.*/"
      },
      "item": {
        "filter": ""
      },
      "itemTag": {
        "filter": ""
      },
      "macro": {
        "filter": ""
      },
      "options": {
        "acknowledged": 1,
        "count": true,
        "disableDataAlignment": false,
        "hostProxy": false,
        "hostsInMaintenance": false,
        "limit": 1001,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "sortProblems": "default",
        "useTimeRange": true,
        "useTrends": "default",
        "useZabbixValueMapping": false
      },
      "proxy": {
        "filter": ""
      },
      "queryType": "4",
      "refId": "C",
      "resultFormat": "time_series",
      "schema": 12,
      "showProblems": "problems",
      "table": {
        "skipEmptyValues": false
      },
      "tags": {
        "filter": ""
      },
      "textFilter": "",
      "trigger": {
        "filter": ""
      }
    },
    {
      "application": {
        "filter": ""
      },
      "countTriggersBy": "",
      "datasource": {
        "type": "alexanderzobnin-zabbix-datasource",
        "uid": "ce7a1xu5vquiof"
      },
      "evaltype": "0",
      "functions": [],
      "group": {
        "filter": "$hgroup"
      },
      "hide": false,
      "host": {
        "filter": "/.*/"
      },
      "item": {
        "filter": ""
      },
      "itemTag": {
        "filter": ""
      },
      "macro": {
        "filter": ""
      },
      "options": {
        "acknowledged": 1,
        "count": true,
        "disableDataAlignment": false,
        "hostProxy": false,
        "hostsInMaintenance": false,
        "limit": 1001,
        "minSeverity": 4,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "sortProblems": "default",
        "useTimeRange": true,
        "useTrends": "default",
        "useZabbixValueMapping": false
      },
      "proxy": {
        "filter": ""
      },
      "queryType": "4",
      "refId": "D",
      "resultFormat": "time_series",
      "schema": 12,
      "showProblems": "problems",
      "table": {
        "skipEmptyValues": false
      },
      "tags": {
        "filter": ""
      },
      "textFilter": "",
      "trigger": {
        "filter": ""
      }
    },
    {
      "application": {
        "filter": ""
      },
      "countTriggersBy": "",
      "datasource": {
        "type": "alexanderzobnin-zabbix-datasource",
        "uid": "ce7a1xu5vquiof"
      },
      "evaltype": "0",
      "functions": [],
      "group": {
        "filter": "$hgroup"
      },
      "hide": false,
      "host": {
        "filter": "/.*/"
      },
      "item": {
        "filter": ""
      },
      "itemTag": {
        "filter": ""
      },
      "macro": {
        "filter": ""
      },
      "options": {
        "acknowledged": 1,
        "count": true,
        "disableDataAlignment": false,
        "hostProxy": false,
        "hostsInMaintenance": false,
        "limit": 1001,
        "minSeverity": 5,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "sortProblems": "default",
        "useTimeRange": true,
        "useTrends": "default",
        "useZabbixValueMapping": false
      },
      "proxy": {
        "filter": ""
      },
      "queryType": "4",
      "refId": "E",
      "resultFormat": "time_series",
      "schema": 12,
      "showProblems": "problems",
      "table": {
        "skipEmptyValues": false
      },
      "tags": {
        "filter": ""
      },
      "textFilter": "",
      "trigger": {
        "filter": ""
      }
    }
  ],
  "datasource": {
    "type": "alexanderzobnin-zabbix-datasource",
    "uid": "ce7a1xu5vquiof"
  },
  "options": {
    "reduceOptions": {
      "values": true,
      "calcs": [
        "lastNotNull"
      ],
      "fields": ""
    },
    "orientation": "horizontal",
    "legend": {
      "showLegend": false,
      "displayMode": "list",
      "placement": "bottom",
      "calcs": []
    },
    "displayMode": "gradient",
    "valueMode": "color",
    "namePlacement": "auto",
    "showUnfilled": true,
    "sizing": "auto",
    "minVizWidth": 8,
    "minVizHeight": 16,
    "maxVizHeight": 300
  }
}

```

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 11.4.0  | 7.0  | 5.0.4             |

Image

Image

### PR DESCRIPTION
**Pull request by zoltanbedi**
Fixes #2002

### CODE REVIEW

File: src/datasource/zabbix/connectors/zabbix_api/zabbixAPIConnector.ts [hunk 1]
```diff
@@ -793,7 +793,7 @@ export class ZabbixAPIConnector {
         triggers = triggers.length;
       }
       // When version is 7.0.0 or higher, groups are returned as hostgroups
-      if (semver.gte(this.version, '7.0.0')) {
+      if (semver.gte(this.version, '7.0.0') && !count) {
         triggers.forEach((trigger) => {
           trigger.groups = trigger.hostgroups;
         });
```
Comment (gwdawson) [inline src/datasource/zabbix/connectors/zabbix_api/zabbixAPIConnector.ts:799]: i noticed this block of code is repeated in a few places. would it make sense to extract it into a separate helper function? so that we can ensure consistency and reduce the risk of these falling out of sync in the future.

just a thought, feel free to ignore.

**Review by gwdawson — APPROVED** [review]
LGTM, works as expected.
